---
name: test
on:
  push:
    branches:
      - develop
    paths:
      - coit-backend1/**
  workflow_dispatch: null
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: temurin
      - name: Read Version
        id: read_version
        run: |
          $config = "DE"
          $fileContent = Get-Content "${{ github.workspace }}\versions.yml"
          $regex = [regex]"$($config):\s*""(.+?)"""
          if ($fileContent -match $regex) {
             $version = $matches[1]
             Write-Output "Version_current: $version"
             echo "::set-output name=version::$version"
          }
        shell: PowerShell
      - name: Increment Version
        id: increment_version
        run: |
          $current_version = $env:INPUT_VERSION
          $incremented_version = $current_version -split'\.'
          $incremented_version[-1] = [int]$incremented_version[-1]+1
          $incremented_version = $incremented_version -join'.'
          Write-Output "Incremented Version: $incremented_version"
          echo "::set-output name=incremented_version::$incremented_version"
        env:
          INPUT_VERSION: ${{ steps.read_version.outputs.version }}
        shell: PowerShell
      - name: Update Version in release-version in versions-de.yml
        run: >
          git stash push -m "Stashing changes in $config"
          git checkout develop
          git pull origin develop
          git reset HEAD .
          git restore --source=HEAD --staged -- .
          git restore --source=HEAD -- .
          git checkout HEAD -- versions.yml
          
          $config = "DE"
          $incremented_version = "${{ steps.increment_version.outputs.incremented_version }}"
          $versions = Get-Content "${{ github.workspace }}\versions.yml" | ConvertFrom-Yaml
          $versions.versions.$config = $incremented_version
          $versions | ConvertTo-Yaml | Set-Content "${{ github.workspace }}\versions.yml"
          git add "${{ github.workspace }}\versions.yml"
          git commit -m "Increment version for $config to $incremented_version"
          git push origin develop
        env:
          INPUT_VERSION: ${{ steps.increment_version.outputs.incremented_version }}
        shell: PowerShell
