---
name: test
on:
  push:
    branches:
      - develop
    paths:
      - coit-backend1/**
  workflow_dispatch: null
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: temurin
      - name: Read Version
        id: read_version
        run: >
          $config = "DE"

          $fileContent = Get-Content "${{ github.workspace }}\versions.yml" | Out-String
          Write-Output "File Content: $fileContent"  # Debugging line
          $regex = [regex]"$($config):\s*""(.+?)"""
          Write-Output "Regex: $regex"  # Debugging line
          if ($fileContent -match $regex) {
          $version = $matches[1]
           Write-Output "Version_current: $version"
           echo "::set-output name=version::$version"
          }
        shell: PowerShell
      - name: Increment Version
        id: increment_version
        run: |
          $current_version = $env:INPUT_VERSION
          $incremented_version = $current_version -split'\.'
          $incremented_version[-1] = [int]$incremented_version[-1]+1
          $incremented_version = $incremented_version -join'.'
          Write-Output "Incremented Version: $incremented_version"
          echo "::set-output name=incremented_version::$incremented_version"
        env:
          INPUT_VERSION: ${{ steps.read_version.outputs.version }}
        shell: PowerShell
      - name: Update Version in release-version in versions-de.yml
        run: >
          # Define the config and read the content of the versions.yml file

          $config = "DE"
          $fileContent = Get-Content "${{ github.workspace }}\versions.yml" | Out-String  # Join lines into one string
          Write-Output "File Content: $fileContent"  # Debugging line
          # Regex to match version for the selected config (e.g., DE)
          $regex = [regex]"$($config):\s*""(.+?)"""  # Corrected regex pattern
          Write-Output "Regex: $regex"  # Debugging line  
          # Perform the regex match
          if ($fileContent -match $regex) {
          $version = $matches[1]
          Write-Output "Version_current: $version"
          echo "::set-output name=version::$version"
          } 

          # Increment the version
          $incremented_version = $version -split '\.' 
          $incremented_version[-1] = [int]$incremented_version[-1] + 1
          $incremented_version = $incremented_version -join '.'
          Write-Output "Incremented Version: $incremented_version"  
          # Replace the version in the file
          $fileContent = $fileContent -replace "$($config):\s*""$version""", "$($config): `"$incremented_version`""
          Set-Content "${{ github.workspace }}\versions.yml" -Value $fileContent
          # Git operations
          git add "${{ github.workspace }}\versions.yml"
          git commit -m "Increment version for $config to $incremented_version"
          git push origin develop
        shell: PowerShell
        env:
          JAVA_HOME: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\11.0.25-9\x64
